name: flutter_printer_manager
description: Flutter plugin for interacting with printers on different platforms with main target to esc pos devices
version: 1.0.0
repository: https://github.com/hallmayer/flutter_printer_manager
issue_tracker: https://github.com/hallmayer/flutter_printer_manager/issues

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: '>=3.3.0'

flutter:  
  plugin:
    platforms:
      android:
        default_package: flutter_printer_manager_android

dependencies:
  flutter:
    sdk: flutter
  network_info_plus: ^6.0.1
  path_provider: ^2.1.4
  logger: ^2.4.0
  plugin_platform_interface: ^2.1.8
  dart_ping: ^9.0.1
  flutter_printer_manager_platform_interface: 
    path: ../flutter_printer_manager_platform_interface
  flutter_printer_manager_android: 
    path: ../flutter_printer_manager_android

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

topics: 
  - escpos
  - printer
  - usb

 
