name: flutter_printer_manager
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: '>=3.3.0'

flutter:  
  plugin:
    platforms:
      android:
        default_package: flutter_printer_manager_android

dependencies:
  flutter:
    sdk: flutter
  network_info_plus: ^6.0.1
  path_provider: ^2.1.4
  logger: ^2.4.0
  plugin_platform_interface: ^2.1.8
  dart_ping: ^9.0.1
  flutter_printer_manager_platform_interface: 
    path: ../flutter_printer_manager_platform_interface
  flutter_printer_manager_android: 
    path: ../flutter_printer_manager_android

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.

 
